name: Build LaTeX document

on:
  push:
    branches: main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          latexmk_use_xelatex: true

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            resume.pdf

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Mao-Lin_focaaby_resume
          path: resume.pdf
